// ?stats frame-time overlay for love.js (generated by build_web.py)
(function () {
  if (!/[?&]stats\b/.test(location.search)) return;
  var raf = window.requestAnimationFrame.bind(window);
  var frames = 0, work = 0, workMax = 0, gapMax = 0, slow = 0, last = 0, t0 = performance.now();
  var box = document.createElement('div');
  box.style.cssText = 'position:fixed;top:4px;right:4px;z-index:1000;padding:4px 8px;' +
    'font:12px/1.4 ui-monospace,monospace;color:#9f9;background:rgba(0,0,0,.7);' +
    'white-space:pre;pointer-events:none';
  document.addEventListener('DOMContentLoaded', function () { document.body.appendChild(box); });
  window.requestAnimationFrame = function (cb) {
    return raf(function (ts) {
      var s = performance.now();
      if (last) { var gap = s - last; gapMax = Math.max(gapMax, gap); if (gap > 34) slow++; }
      last = s;
      cb(ts);
      var w = performance.now() - s;
      work += w; workMax = Math.max(workMax, w); frames++;
      if (s - t0 >= 1000) {
        box.textContent = (frames * 1000 / (s - t0)).toFixed(0) + ' fps   ' +
          'work ' + (work / frames).toFixed(1) + ' ms avg / ' + workMax.toFixed(0) + ' max\n' +
          'longest gap ' + gapMax.toFixed(0) + ' ms   frames >34ms: ' + slow + '\n' +
          (navigator.userAgent.match(/(Firefox|Chrome|Version)\/[\d.]+/) || [''])[0].replace('Version', 'Safari');
        frames = work = workMax = gapMax = slow = 0; t0 = s;
      }
    });
  };
})();
