// keyboard fixes for love.js (generated by build_web.py)
function fixKey(e) {
  if (e.location === 3 && e.code && !/^Numpad/.test(e.code))
    Object.defineProperty(e, 'location', { value: 0 });
}
window.addEventListener('keydown', function (e) {
  fixKey(e);
  if (e.metaKey || /^F\d+$/.test(e.key)) return;
  e.preventDefault();
}, true);
window.addEventListener('keyup', fixKey, true);
