// WebGL 1 fix for love.js (generated by build_web.py): 8-bit canvases
(function () {
  var P = window.WebGLRenderingContext && WebGLRenderingContext.prototype;
  if (!P) return;
  var list = P.getSupportedExtensions;
  P.getSupportedExtensions = function () {
    var exts = list.call(this) || [];
    return exts.indexOf('OES_rgb8_rgba8') < 0 ? exts.concat('OES_rgb8_rgba8') : exts;
  };
})();
